import React from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import {
  AttentionText,
  TitleText,
  GradientText,
  Build,
  Button,
  Logos,
} from "@/components/home";
import styles from "@/styles/Home.module.scss";
import HomePopup from "../components/home/home-popup";

export default function Home() {
  const [isOpen, setIsOpen] = React.useState(false);
  const [isSend, setIsSend] = React.useState(false);

  return (
    <>
      <Head>
        <title>ARTIMA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <AttentionText />
        <TitleText />
        <GradientText />
        <Build />
        <Button />
        <Logos />
      </main>
      {isOpen && <HomePopup />}
    </>
  );
}
